from __future__ import annotations


SHARED_FOOD_TEST_LAYERS = {
    "logic": (
        "test_shared_food_partner_rules",
        "test_shared_food_outcome_rules",
    ),
    "runtime": (
        "test_item_scene_coordinator",
        "test_offer_interaction_rules",
        "test_offer_release_ui",
        "test_shared_food_runtime",
    ),
    "assets": (
        "test_asset_manager",
        "test_asset_action_audit",
        "test_manifest_xlsx_converter",
        "test_shared_food_asset_integration",
    ),
}


TEST_SUITE_MEMBERS = {
    "assets": {
        "test_asset_loader",
        "test_asset_manager",
        "test_asset_selection_rules",
        "test_asset_store",
        "test_manifest_rules",
        "test_race_asset_integration",
        "test_ui_skin_assets",
    },
    "config": {
        "test_config_apply_coordinator",
        "test_config_rules",
        "test_config_save_scheduler",
        "test_config_store",
    },
    "dashboard": {
        "test_dashboard_actions",
        "test_dashboard_controller",
        "test_dashboard_information_center_state",
        "test_dashboard_launcher_ui",
        "test_dashboard_presenter",
        "test_dashboard_shell_lifecycle",
        "test_dashboard_shell_rules",
        "test_dashboard_shutdown_controller",
        "test_dashboard_state_mapper",
        "test_dashboard_tools_actions",
        "test_event_log_ui",
        "test_family_summary_ui",
        "test_information_center_spec",
        "test_information_center_size_rules",
        "test_information_center_state",
        "test_information_center_ui",
        "test_offer_tray_ui",
        "test_relation_summon_ui",
        "test_skinned_window_frame",
        "test_status_settings_ui",
        "test_transformation_control_presenter",
        "test_ui_localization",
        "test_ui_skin_spec",
        "test_window_chrome",
    },
    "pet": {
        "test_pet_ambient_mood_rules",
        "test_pet_ai_scheduler",
        "test_pet_behavior_scheduler",
        "test_pet_collision_rules",
        "test_pet_logic",
        "test_pet_overlay_renderer",
        "test_pet_intent_rules",
        "test_pet_observe_rules",
        "test_pet_physics",
        "test_pet_perception_rules",
        "test_pet_random_rules",
        "test_pet_relationship_rules",
        "test_pet_runtime_state",
        "test_pet_social_care",
        "test_pet_social_catalog",
        "test_pet_social_coordinator",
        "test_pet_social_effects",
        "test_pet_social_log_rules",
        "test_pet_social_rules",
        "test_pet_tick_coordinator",
        "test_pet_widget_runtime",
    },
    "runtime": {
        "test_activity_rhythm",
        "test_bottle_honey_scene_executor",
        "test_direct_hover_scene_executor",
        "test_ground_item_coordinator",
        "test_household_event_rules",
        "test_household_persistence",
        "test_household_runtime_coordinator",
        "test_item_scene_coordinator",
        "test_offer_interaction_runtime",
        "test_offer_release_ui",
        "test_race_executor",
        "test_race_event_adapter",
        "test_race_profiles",
        "test_race_rules",
        "test_household_state",
        "test_offer_interaction_rules",
        "test_runtime_clock",
        "test_shared_food_outcome_rules",
        "test_shared_food_partner_rules",
        "test_shared_food_runtime",
        "test_shared_food_scene_executor",
        "test_shared_food_asset_integration",
    },
    "tooling": {
        "test_asset_action_audit",
        "test_lab_2_entrypoint",
        "test_manifest_xlsx_converter",
        "test_manifest_xlsx_tool",
        "test_suite_catalog",
        "test_tooling_lightweight_checks",
    },
    "windowing": {
        "test_pet_windowing_effects",
        "test_window_mode_rules",
        "test_window_motion",
        "test_window_perch_rules",
        "test_window_surface_rules",
        "test_window_surface_selector",
        "test_window_tracker_facade",
        "test_window_tracker_policy",
        "test_windowing_coordinator",
    },
}


def classify_test_module(module_name: str) -> str:
    module_stem = module_name.rsplit(".", 1)[-1]
    for suite_name, members in TEST_SUITE_MEMBERS.items():
        if module_stem in members:
            return suite_name
    return "uncategorized"
